version: '3.6'
# https://ithelp.ithome.com.tw/articles/10211148
# https://docs.gitlab.com/ee/install/docker.html
# get root password
# docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password 
services:
  web:
    image: 'gitlab/gitlab-ee:15.1.2-ee.0'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
    ports:
      - '80:80'
      - '443:443'
      - '9999:22'
    volumes:
      - 'config:/etc/gitlab'
      - 'logs:/var/log/gitlab'
      - 'data:/var/opt/gitlab'
    shm_size: '256m'

volumes:
  config:
  logs:
  data: